# Generated by Django 3.2 on 2021-07-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_friend_list_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieve_request',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sent_request',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
