# Generated by Django 3.2 on 2021-07-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210717_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_url',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to='bills'),
        ),
    ]
