# Generated by Django 3.2 on 2021-07-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20210717_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='creator',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
