# Generated by Django 3.2 on 2021-07-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_friend_list_friend_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
