# Generated by Django 3.2 on 2021-07-17 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_bill_bill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
