# Generated by Django 3.2.7 on 2021-09-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_list',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='friend_list',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recieve_request',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='recieve_request',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='sent_request',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='sent_request',
            name='to_user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='bill',
        ),
        migrations.DeleteModel(
            name='friend_list',
        ),
        migrations.DeleteModel(
            name='recieve_request',
        ),
        migrations.DeleteModel(
            name='sent_request',
        ),
    ]
