# Generated by Django 3.2.7 on 2021-09-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='img',
            field=models.CharField(max_length=100),
        ),
    ]
